stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
          timestampable: true
          sluggable: true

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: "Dime\TimetrackerBundle\Entity\User"

# JMSSerializerBundle (required by FosRestBundle)
jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
            default_timezone: "UTC"

    property_naming:
        separator: _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

fos_rest:
    routing_loader:
        default_format:       null
    service:
        router:               router
        templating:           templating
        serializer:           jms_serializer.serializer
        view_handler:         fos_rest.view_handler.default
    view:
#        default_engine:       twig
        force_redirects:
           html: false
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
        view_response_listener:  force
        failed_validation:       HTTP_BAD_REQUEST
    exception:
        codes: ~
        messages: ~
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    format_listener:
        default_priorities:   [html, */*]
        prefer_extension:     true
        fallback_format:      html

parameters:
    # overwrite default pagination parameters
    pagination:
        offset: 0
        limit:  10
