activities:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\ActivitiesController
    prefix:   /api
    defaults: { _format: json }

customers:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\CustomersController
    prefix:   /api
    defaults: { _format: json }

projects:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\ProjectsController
    prefix:   /api
    defaults: { _format: json }

services:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\ServicesController
    prefix:   /api
    defaults: { _format: json }

settings:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\SettingsController
    prefix:   /api
    defaults: { _format: json }

timeslices:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\TimeslicesController
    prefix:   /api
    defaults: { _format: json }

tags:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\TagsController
    prefix:   /api
    defaults: { _format: json }

users:
    type:     rest
    resource: Dime\TimetrackerBundle\Controller\UsersController
    prefix:   /api
    defaults: { _format: json }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
