<?php

namespace Dime\TimetrackerBundle\Entity;

use Dime\TimetrackerBundle\Entity\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    /**
     * Search
     * Not implemented yet.
     *
     * @param string            $text
     * @param QueryBuilder      $qb
     *
     * @return QueryBuilder
     */
    public function search($text, QueryBuilder $qb)
    {
        return $qb;
    }

    /**
     * Scope by date,
     * Not implemented yet.
     *
     * @param                   $date
     * @param QueryBuilder      $qb
     *
     * @return QueryBuilder
     */
    public function scopeByDate($date, QueryBuilder $qb)
    {
        return $qb;
    }

    /**
     * Filter by namespace
     *
     * @param                            $namespace
     * @param QueryBuilder $qb
     *
     * @return QueryBuilder
     */
    public function scopeByNamespace($namespace, QueryBuilder $qb)
    {
        return $this->scopeByField('namespace', $namespace, $qb);
    }
}
