activities:
    resource: Dime\TimetrackerBundle\Controller\ActivitiesController
    type:     rest

customers:
    resource: Dime\TimetrackerBundle\Controller\CustomersController
    type:     rest

project:
    resource: Dime\TimetrackerBundle\Controller\ProjectsController
    type:     rest

services:
    resource: Dime\TimetrackerBundle\Controller\ServicesController
    type:     rest
