activities:
    resource: Dime\TimetrackerBundle\Controller\ActivitiesController
    type:     rest

customers:
    resource: Dime\TimetrackerBundle\Controller\CustomerController
    type:     rest

project:
    resource: Dime\TimetrackerBundle\Controller\ProjectController
    type:     rest

services:
    resource: Dime\TimetrackerBundle\Controller\ServicesController
    type:     rest
